// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByOXTDGyarzYcctKRhs2sAJpmf7cp7DZk',
    appId: '1:241102914119:web:909a2c3f41fa4816af6762',
    messagingSenderId: '241102914119',
    projectId: 'toboto-work',
    authDomain: 'toboto-work.firebaseapp.com',
    storageBucket: 'toboto-work.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-dldUnJrQWIOGVfHrj0FbzywYxRhAIsA',
    appId: '1:241102914119:android:344183ccc2812e0faf6762',
    messagingSenderId: '241102914119',
    projectId: 'toboto-work',
    storageBucket: 'toboto-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeMgwp1myzCqvmpAY9q4YgPDxqzHoDOe8',
    appId: '1:241102914119:ios:6cbd2cea1a8e06a3af6762',
    messagingSenderId: '241102914119',
    projectId: 'toboto-work',
    storageBucket: 'toboto-work.appspot.com',
    iosBundleId: 'com.example.tobetowork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeMgwp1myzCqvmpAY9q4YgPDxqzHoDOe8',
    appId: '1:241102914119:ios:5b7cc6c0d5e96e37af6762',
    messagingSenderId: '241102914119',
    projectId: 'toboto-work',
    storageBucket: 'toboto-work.appspot.com',
    iosBundleId: 'com.example.tobetowork.RunnerTests',
  );
}
